export const QueryKey = {
  USER_DONATION_INVENTORY_LIST: "USER_DONATION_INVENTORY_LIST",
  MARKETPLACE_LIST: "MARKETPLACE_LIST",
  PICKEDUP_LIST: "PICKEDUP_LIST",
  USER_DASHBOARD_STATS : "USER_DASHBOARD_STATS",
  USER_FEED_LIST: "USER_FEED_LIST"
};
